name: Yarn Test

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Installing Yarn globally
        run: npm install --global yarn

      - name: Installing application dependencies
        run: yarn

      - name: Testing
        run: yarn test
